### ISSUE TITLE
Have course init repo function pull from Google Sheet

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/rfortherestofus#2]
It's going to be easier for me if I can have all issues/milestones in a Google Sheet. I've created one [here](https://docs.google.com/spreadsheets/d/1iIX8pGBpyePUVI1iiy89e6pDqrNFa_RXZkRVuB4vjA0/edit?usp=sharing). It's got a sheet with issues and a separate one with milestones. Can you please adjust the function so it pulls from this sheet in order to create the issues/milestones?

**Comment by tvroylandt** [comment]
Just a reminder for myself : code to clean here : https://github.com/rfortherestofus/rfortherestofus/commit/9d75a9505dab4ca6100832522219f4acf75d4c7d

**Comment by tvroylandt** [comment]
Same as https://github.com/rfortherestofus/rfortherestofus/issues/3
