### ISSUE TITLE
Set milestone due dates

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/rfortherestofus#3]
When creating a list of issues/milestones on a new course repo, it would be helpful to be able to set due dates for milestones automatically. Can we do the following?

Add an argument to the `init_course_repo()` function for course_release_date. When I enter this, it will automatically calculate due dates for certain milestones as follows:

- Curriculum Development: 2 months before course release date
- Recording: 1 month before course release date
- Video Editing: 2 weeks before course release date
- Marketing: 1 week before course release date

Let me know if you have any questions. Thanks!

**Comment by tvroylandt** [comment]
Ok. I made something here : https://github.com/rfortherestofus/rfortherestofus/commit/42266ebc46788fa02ac7b036545378ac8b517318

I will change it so that the due date can be setup in the Sheets file as in https://github.com/rfortherestofus/rfortherestofus/issues/2#event-5361481369

**Comment by dgkeyes** [comment]
Looks great! Please proceed with #2. Thanks.

**Comment by tvroylandt** [comment]
Done here : https://github.com/rfortherestofus/rfortherestofus/pull/4

Just change the google sheets and everything will follow

**Comment by dgkeyes** [comment]
Sorry, just realized I never responded to this. All set. Thanks!
